-- MySQL Script generated by MySQL Workbench
-- 03/02/16 08:34:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema jobbank
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `jobbank` ;

-- -----------------------------------------------------
-- Schema jobbank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jobbank` DEFAULT CHARACTER SET latin1 ;
USE `jobbank` ;

-- -----------------------------------------------------
-- Table `jobbank`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobbank`.`comments` ;

CREATE TABLE IF NOT EXISTS `jobbank`.`comments` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user` INT(11) NOT NULL,
  `timestamp` DATETIME NOT NULL,
  `project` INT(11) NOT NULL,
  `task` INT(11) NOT NULL,
  `comment` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 53
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jobbank`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobbank`.`user` ;

CREATE TABLE IF NOT EXISTS `jobbank`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(30) CHARACTER SET 'utf8' NOT NULL,
  `password` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `firstname` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `lastname` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `email` VARCHAR(30) CHARACTER SET 'utf8' NOT NULL,
  `gender` VARCHAR(10) CHARACTER SET 'utf8' NOT NULL,
  `phoneNumber` VARCHAR(15) CHARACTER SET 'utf8' NOT NULL,
  `dateOfBirth` DATE NOT NULL,
  `nameWithInitials` VARCHAR(30) CHARACTER SET 'utf8' NOT NULL,
  `nic` VARCHAR(15) CHARACTER SET 'utf8' NOT NULL,
  `mobilenumber` VARCHAR(15) CHARACTER SET 'utf8' NOT NULL,
  `accesslevel` VARCHAR(15) CHARACTER SET 'utf8' NOT NULL,
  `address` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `city` VARCHAR(15) CHARACTER SET 'utf8' NOT NULL,
  `country` VARCHAR(15) CHARACTER SET 'utf8' NOT NULL,
  `Pillar` TEXT CHARACTER SET 'utf8' NOT NULL,
  `Department` TEXT CHARACTER SET 'utf8' NOT NULL,
  `Batch` TINYINT(4) NOT NULL,
  `Skills` TEXT CHARACTER SET 'utf8' NOT NULL,
  `status` SMALLINT(11) NULL DEFAULT '-1',
  `photopath` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `cvpath` TEXT NULL,
  `lastlogin` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 96
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `username` ON `jobbank`.`user` (`username` ASC);

CREATE UNIQUE INDEX `nic` ON `jobbank`.`user` (`nic` ASC);

CREATE UNIQUE INDEX `email` ON `jobbank`.`user` (`email` ASC, `mobilenumber` ASC);


-- -----------------------------------------------------
-- Table `jobbank`.`confirmation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobbank`.`confirmation` ;

CREATE TABLE IF NOT EXISTS `jobbank`.`confirmation` (
  `id` INT(11) NOT NULL,
  `email` TEXT NOT NULL,
  `verification` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_confirmation_user1`
    FOREIGN KEY (`id`)
    REFERENCES `jobbank`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `fk_confirmation_user1_idx` ON `jobbank`.`confirmation` (`id` ASC);


-- -----------------------------------------------------
-- Table `jobbank`.`event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobbank`.`event` ;

CREATE TABLE IF NOT EXISTS `jobbank`.`event` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `teamleader` INT(11) NOT NULL,
  `project` INT(11) NOT NULL,
  `weight` INT(11) NOT NULL,
  `description` LONGTEXT CHARACTER SET 'utf8' NOT NULL,
  `goals` TEXT CHARACTER SET 'utf8' NOT NULL,
  `members` LONGTEXT CHARACTER SET 'utf8' NOT NULL COMMENT '(DC2Type:array)',
  `starttimestamp` TEXT CHARACTER SET 'utf8' NOT NULL,
  `endtimestamp` TEXT CHARACTER SET 'utf8' NOT NULL,
  `duetimestamp` TEXT CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jobbank`.`notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobbank`.`notification` ;

CREATE TABLE IF NOT EXISTS `jobbank`.`notification` (
  `id` INT(11) NOT NULL,
  `userid` INT(11) NOT NULL,
  `heading` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `details` TEXT CHARACTER SET 'utf8' NOT NULL,
  `timestamp` TEXT CHARACTER SET 'utf8' NOT NULL,
  `project` INT(11) NOT NULL,
  `task` INT(11) NOT NULL,
  `seen` TINYINT(4) NULL DEFAULT '0',
  `type` SMALLINT(6) NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_notification_user`
    FOREIGN KEY (`userid`)
    REFERENCES `jobbank`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 126
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_notification_user_idx` ON `jobbank`.`notification` (`userid` ASC);


-- -----------------------------------------------------
-- Table `jobbank`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobbank`.`project` ;

CREATE TABLE IF NOT EXISTS `jobbank`.`project` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) CHARACTER SET 'utf8' NOT NULL,
  `start` TEXT CHARACTER SET 'utf8' NOT NULL,
  `end` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `due` TEXT CHARACTER SET 'utf8' NOT NULL,
  `manager` INT(11) NOT NULL,
  `members` LONGTEXT CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '(DC2Type:array)',
  `description` TEXT CHARACTER SET 'utf8' NOT NULL,
  `objectives` TEXT CHARACTER SET 'utf8' NOT NULL,
  `status` TINYINT(4) NOT NULL DEFAULT '0',
  `subscribers` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `comments` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `name` ON `jobbank`.`project` (`name` ASC);


-- -----------------------------------------------------
-- Table `jobbank`.`task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobbank`.`task` ;

CREATE TABLE IF NOT EXISTS `jobbank`.`task` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `completed` TINYINT(4) NULL DEFAULT '0',
  `name` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `type` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `user` VARCHAR(30) CHARACTER SET 'utf8' NOT NULL,
  `leader` VARCHAR(30) CHARACTER SET 'utf8' NOT NULL,
  `project` VARCHAR(30) CHARACTER SET 'utf8' NOT NULL,
  `weight` INT(11) NOT NULL,
  `description` LONGTEXT CHARACTER SET 'utf8' NOT NULL,
  `goals` TEXT CHARACTER SET 'utf8' NOT NULL,
  `starttimestamp` TEXT CHARACTER SET 'utf8' NOT NULL,
  `endtimestamp` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `duetimestamp` TEXT CHARACTER SET 'utf8' NOT NULL,
  `comments` LONGTEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `pillar` TEXT CHARACTER SET 'utf8' NOT NULL,
  `rate` INT(4) NOT NULL DEFAULT '0',
  `subscribers` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 100
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `name` ON `jobbank`.`task` (`name` ASC);


-- -----------------------------------------------------
-- Table `jobbank`.`trackreport`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobbank`.`trackreport` ;

CREATE TABLE IF NOT EXISTS `jobbank`.`trackreport` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `User` INT(11) NOT NULL,
  `OverallRating` DOUBLE NULL DEFAULT '0',
  `TotalWeight` INT(11) NOT NULL,
  `Comments` LONGTEXT CHARACTER SET 'utf8' NOT NULL COMMENT '(DC2Type:array)',
  `Projects` LONGTEXT CHARACTER SET 'utf8' NOT NULL COMMENT '(DC2Type:array)',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 58
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `User` ON `jobbank`.`trackreport` (`User` ASC);


-- -----------------------------------------------------
-- Table `jobbank`.`vacancy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jobbank`.`vacancy` ;

CREATE TABLE IF NOT EXISTS `jobbank`.`vacancy` (
  `organizationName` VARCHAR(200) NOT NULL,
  `contactName` VARCHAR(100) NULL,
  `contactDesignation` VARCHAR(50) NULL,
  `contactEmail` VARCHAR(30) NOT NULL,
  `contactNumber` VARCHAR(15) NULL,
  `availablePosition` VARCHAR(15) NOT NULL,
  `noOfVacancies` INT(11) NULL,
  `heading` VARCHAR(50) NOT NULL,
  `description` VARCHAR(500) NULL,
  `imagePath` TEXT NULL,
  `applyBeforeDate` DATETIME NOT NULL,
  `creationDate` DATETIME NOT NULL,
  `postedByUserID` INT(11) NOT NULL,
  PRIMARY KEY (`organizationName`),
  CONSTRAINT `fk_vacancy_user1`
    FOREIGN KEY (`postedByUserID`)
    REFERENCES `jobbank`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_vacancy_user1_idx` ON `jobbank`.`vacancy` (`postedByUserID` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
