vacancy_index:
    pattern:  /vacancy/index
    defaults: { _controller: VacancyBundle:VacancyList:viewList }

vacancy_detail:
    pattern:  /vacancy/view/{vacancyId}
    defaults: { _controller: VacancyBundle:VacancyView:viewVacancy }

vacancy_new:
    pattern:  /vacancy/new
    defaults: { _controller: VacancyBundle:VacancyCreate:newVacancy }

vacancy_edit:
    pattern:  /vacancy/edit/{vacancyId}
    defaults: { _controller: VacancyBundle:VacancyUpdate:editVacancy }

vacancy_edit_image:
    pattern:  /vacancy/editImage/{vacancyId}
    defaults: { _controller: VacancyBundle:VacancyUpdate:editVacancyImage }

vacancy_delete:
    pattern:  /vacancy/delete/{vacancyId}
    defaults: { _controller: VacancyBundle:VacancyDelete:deleteVacancy }