parameters:
#    bundle_vacancy.example.class: Bundle\VacancyBundle\Example

services:
#    bundle_vacancy.example:
#        class: %bundle_vacancy.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
